<?php 
/**
 * Pereira, Thiago Santos
 * http://thiagosantos.com/
 *
 * @category   ThiagoSantos
 * @package    ThiagoSantos_CarrinhoAbandonado
*/

$_customer = $this->getCustomer();
$_quote = $this->getQuote();




?>
<table width="100%" cellspacing="0" cellpadding="0" border="0" style="border:1px solid #bebcb7;background:#f8f7f5">
      <thead>
            <tr>
                  <th align="left" bgcolor="#d9e5ee" style="padding:3px 9px">Item</th>
                  <th align="left" bgcolor="#d9e5ee" style="padding:3px 9px">ID do produto</th>
                  <th align="center" bgcolor="#d9e5ee" style="padding:3px 9px">Qtde</th>
                  <th align="right" bgcolor="#d9e5ee" style="padding:3px 9px">Subtotal</th>
            </tr>
      </thead>
      <?php $i=0; foreach($_quote->getAllItems() as $item ): ?>
            
      <tbody <?php echo $i%2 ? 'bgcolor="#eeeded"' : '';?>>
            <tr>
                  <td align="left" valign="top" style="padding:3px 9px"><strong><?php echo $item -> getName();?></strong></td>
                  <td align="left" valign="top" style="padding:3px 9px"><?php echo $item -> getSku();?></td>
                  <td align="center" valign="top" style="padding:3px 9px"><?php echo $item -> getQty();?></td>
                  <td align="right" valign="top" style="padding:3px 9px"><span> <?php echo Mage::helper('core')->currency( $item->getRowTotal(),true,false); ?> </span></td>
            </tr>
      </tbody>
      <?php $i++; endforeach;?>

      <?php
      if($_quote->getSubtotal()):
            ?>
      <tfoot>
            <tr>
                  <td align="right" style="padding:3px 9px" colspan="3">Subtotal</td>
                  <td align="right" style="padding:3px 9px"><span><?php echo Mage::helper('core')->currency( $_quote->getSubtotal(),true,false); ?></span></td>
            </tr>
      </tfoot>
      <?php
      endif;
      ?>
</table>
